---
- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted

- name: reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded

- name: reload firewalld
  ansible.builtin.command:
    cmd: firewall-cmd --reload
